version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${MOVIE_REVIEW_DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    restart: on-failure
  web:
    depends_on:
      - db
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' -e production"
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
      DB_HOST: db
      DB_NAME: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      MOVIE_REVIEW_DATABASE_PASSWORD: ${MOVIE_REVIEW_DATABASE_PASSWORD}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      DEFAULT_PER_PAGE: ${DEFAULT_PER_PAGE}
    restart: on-failure
  nginx:
    depends_on: 
      - web
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - "80:80"
    restart: on-failure