ActiveRecord::Base.connection.execute("TRUNCATE publishers RESTART IDENTITY")
Publisher.create!(name: "NXB Kim Đồng", logo: "/images/publishers/kimdong.png")
Publisher.create!(name: "NXB Trẻ", logo: "/images/publishers/nxb_tre.png")
Publisher.create!(name: "TVM Comics", logo: "/images/publishers/tvm.jpg")
Publisher.create!(name: "TABooks", logo: "/images/publishers/tabooks.png")
Publisher.create!(name: "AMAK", logo: "/images/publishers/amak.png")
Publisher.create!(name: "NXB Thanh Niên", logo: "/images/publishers/thanh_nien.png")
Publisher.create!(name: "IMP", logo: "/images/publishers/ipm.png")
